[step.copy-ignored]
exclude = ["node_modules/", "dist/"]

[pre-start]
copy = "wt step copy-ignored"

[[post-start]]
install = "bun install"
[[post-start]]
build = "bun run build"

[pre-merge]
test = "bun run test:docker"
